openapi: 3.0.0
info:
  version: 1.0.0
  title: api.mellonis.ru
servers:
  -   url: 'https://api.mellonis.ru'
paths:
  /clearCache:
    post:
      summary: 'Clears server cache'
      operationId: clearCache
      tag:
        - cache
      responses:
        '200':
           description: 'Cache has been cleared'
  /sectionTypes:
    get:
      summary: 'Returns list of section types'
      operationId: listSectionType
      tag:
        - section
        - type
      responses:
        '200':
          description: 'List of section types'
          headers:
            ETag:
              description: Cache-Control value
              schema:
                type: string
          content:
            allpication/json:
              schema:
                $ref: '#/components/schemas/SetcionTypes'
  /sections:
    get:
      summary: 'Returns list of sections'
      operationId: listSection
      tags:
        - section
      responses:
        '200':
          description: 'List of sections'
          headers:
            ETag:
              description: Cache-Control value
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sections'
        '500':
  /sections/{sectionId}:
    get:
      summary: 'Returns list of things in the section'
      operationId: listThing
      tags:
        - section
        - thing
      responses:
        '200':
          description: 'List of things in the section'
          headers:
            ETag:
            description: Cache-Control value
            schema:
              type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Things'

components:
  schemas:
    SectionTypes:
      type: array
      items:
        type: SectionType
    SectionType:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
    Sections:
      type: array
      items:
        type: Section
    Section:
      type: object
      properties:
        id:
          type: string
        typeId:
          type: number
        title:
          type: string
        description:
          type:
            - string
            - null
        settings:
          type:
            - object
            - string
            - null
    Things:
      type: array
      items: Thing
    Thing:
      type: object
      properties:
        id: number,
        position:
          type: number
        categoryId:
          type: number
        title:
          type:
            - string
            - null
        startDate:
          type:
            - string
            - null
        finishDate:
          type: string
        body:
          type: string
        meta:
          type:
            - null
            - string
            - object