name: Deploy

on:
  pull_request:
    branches:
      - master
    types: [ opened, synchronize, reopened, closed ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test

  build-and-deploy:
    needs: ci
    if: github.event.pull_request.merged == true
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Build image
        run: docker build . -t api.mellonis.ru
      - name: Save image
        run: docker save api.mellonis.ru | gzip > api.mellonis.ru.tar.gz
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Copy image
        env:
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_TARGET: ${{secrets.SSH_TARGET}}
        run: scp -o StrictHostKeyChecking=no ./api.mellonis.ru.tar.gz $SSH_USER@$SSH_HOST:$SSH_TARGET
      - name: Run container
        env:
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_USER: ${{secrets.SSH_USER}}
          SSH_TARGET: ${{secrets.SSH_TARGET}}
        run: ssh $SSH_USER@$SSH_HOST "cd $SSH_TARGET && ./run-poetry.api.sh"


